import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "@/components";
import { BookingProvider } from "@/context/BookingContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const GOOGLE_API_KEY = 'AIzaSyA79Ieh37HYeFhZnFXp-Tg7Od4AS_X6Uyo'
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-900">
        {/* Header */}
        <Header />
        {/* Main Content */}
        <BookingProvider>{children}</BookingProvider>
        {/* Footer */}
        <Footer />
      </body>
      <script
        src={`https://maps.googleapis.com/maps/api/js?key=${GOOGLE_API_KEY}&libraries=places`}
        async
      ></script>
    </html>
  );
}
